progression:
  base-xp: 1500
  multiplier: 1.08

titles:
  newbie:
    display: Newbie
    color: a
    bold: false
    italic: false

  degenerate:
    display: Degenerate
    color: c
    bold: false
    italic: false

  beta:
    display: Beta
    color: d
    bold: true
    italic: false