progression:
  base-xp: 1500
  multiplier: 1.08

titles:
  newbie:
    display: Newbie
    format: lime
    bold: false
    italic: false

  degenerate:
    display: Degenerate
    format: red
    bold: false
    italic: false

  beta:
    display: Beta
    format: pink
    bold: true
    italic: false